# Generated by Django 4.0.4 on 2022-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_ses',
            field=models.BooleanField(default=False, verbose_name='Simple Electronic Signature'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ses',
            field=models.BooleanField(default=False, verbose_name='Simple Electronic Signature'),
        ),
    ]
