# Generated by Django 4.0.4 on 2022-07-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
    ]
